# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UCAMC — UChicago Applied Math Club
email: uchicago.amc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the webpage for the University of Chicago's undergraduate "applied math club". We are a registered student organization (RSO) that hosts
  talks for UChicago undergraduates on topics in applied math. The purpose of this webpage is to serve as an archive of previous talks and club board members.
baseurl: ""
url: "https://ucamc.github.io"
listhost: "https://lists.uchicago.edu/web/info/applied_math_club"
facebookurl: "https://www.facebook.com/groups/ucamc"
github_username: ucamc
currentf: spring21



# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
